-- Content seeded from VP Participant Guide + Reference Guide (adapted for 2026)

INSERT INTO admin_content_blocks (key, content) VALUES
(
  'orienting_artifact',
  E'## Purpose\n\nThe purpose of the Village Playground gathering is to **explore and practice villaging together**.\n\nFor us, villaging is the practice of cultivating interdependent, high-trust relationships of mutual support and thrival.\n\nVillaging has a lot to do with the relationship between the individual and the collective. How do we honour ourselves — our own basis of knowing what''s important — and also be connected and in harmony with something bigger and different than us?\n\n## Principles\n\nThink of these as playful reminders that help us stay in connection with ourselves and one another:\n\n- **Care for all beings**\n- **Follow the aliveness**\n- **Welcome everything as learning**\n- **Participate with the system''s flow**\n- **Expand your perspective**\n\n## Practices\n\nThese short practices are like training wheels that help put our principles into action.\n\n**Practice 1: Noticing and naming**\n1. Listen to my body, feelings and thoughts\n2. Share the data with "I" statements\n\n**Practice 2: Welcoming and integrating**\n1. Turn towards the experience of myself and others with curiosity and compassion\n2. See a whole that includes all parts\n\n**Practice 3: Law of two feet**\n1. Trust the wisdom of my body\n2. Use my feet to move me to the place I''m able to learn, participate and have fun.'
),
(
  'payment_instructions',
  E'## Registration costs\n\n- **$350 CAD** — full 4-day gathering (Sept 25 evening through Sept 29)\n- **$400 CAD** — includes the optional **"Now What" day** (Sept 30)\n- Children under 5 are free\n- USD equivalents: **~$254 USD** / **~$290 USD**\n\nIf you need to pay less, or want to contribute more, say so in the registration survey — we want you here.\n\n## How to pay (in order of preference)\n\n1. **Interac e-transfer (preferred for Canadians):** tessmhart@gmail.com\n2. **Wise:** teresah396 (USD or CAD, without conversion)\n3. **PayPal CAD:** https://paypal.me/pathwaystosource\n4. **PayPal USD:** paypal.me/bakejam\n5. **Venmo USD:** @james-a-baker\n\n## After paying\n\nCheck **"I have sent my payment"** in your profile, or **"I will pay by Aug 31"** if you''re committing to pay soon. These checkboxes are how the host crew tracks payment status.'
),
(
  'participant_guide',
  E'## Dates & times (2026)\n\n- Gathering begins **Sept 25 evening**\n- Full days **Sept 26–28**\n- Main gathering concludes **Sept 29 @ 1pm**\n- Optional **"Now What" day** — Sept 30, checkout @ 2pm\n\n## Location\n\n**Camp Ki-Wa-Y**\n3738 Hessen Strasse, St. Clements, ON N0B 2M0\n(Right outside Waterloo, Ontario — ~1 hr from Toronto Pearson)\n\nPlease reach out to the host crew before calling the camp directly.\n\n## Getting there\n\n| From | To | Option | Notes |\n|------|-----|--------|-------|\n| Toronto Union | Kitchener | GO Train | ~2 hrs |\n| Pearson | UW | GO Bus | ~2 hrs, 1 transfer |\n| Kitchener terminal | Camp | Uber/Lyft | ~35 min — split with others! |\n| Toronto / Pearson | Camp | Uber/Lyft | 1–1.5 hrs — split with others! |\n\nCarpool coordination will happen in the Logistics Hub once you''re registered.\n\n## Accommodations\n\n- Bunk beds in cabins (rooms of 8–12 people) — bring your own sheets and pillow\n- Some tenting available — let us know in registration if you can tent\n- Tell us who you''d like to bunk with when you register\n\n## Food\n\nHealthy, kid-friendly meals prepared by camp staff 3× daily. Vibrant salad bar at lunch and dinner. Snacks available 24hrs in the Sanctuary.\n\nThe facility is **nut-free** in public spaces. Let us know dietary restrictions in registration.\n\n## Technology\n\nWe''re here for quality time in nature — internet and electronics are discouraged. Wi-Fi is available in the dining hall (Paradise Post). Mediocre cell service throughout the land.\n\n## What to bring\n\n- Sleeping bag or blanket + fitted sheet, pillow\n- Towel, toiletries, refillable water bottle\n- Indoor shoes, outdoor/hiking shoes or rain boots\n- Warm layers (evenings can be 10–15°C), bathing suit, sun hat\n- Ear plugs / eye mask if you''re a light sleeper\n- Optional: camp chair, games/cards, crafts to share\n\n## Camp activities (staff-led)\n\nLow ropes, rock climbing, archery, high ropes, waterfront with canoes/kayaks/swimming — offered at designated times each afternoon. Open Space sessions let anyone host an activity or conversation.'
),
(
  'camp_agreements',
  E'## Camp agreements\n\nThese agreements help us maintain good relationships with Camp Ki-Wa-Y:\n\n- **Quiet hours:** 10pm–8am (respect babies, neighbours, and camp staff)\n- **Smoke, drug, and alcohol-free** camp\n- **Nut-free** in public spaces — don''t consume nuts where others gather\n- **Waterfront** only when a lifeguard is present\n- **Photos & videos** may be taken for sharing among us — ask for consent before sharing publicly\n\n## Camp tips\n\n- Wi-Fi instructions posted in Paradise Post (dining hall)\n- Aim to be present at the start of meal times\n- Snacks available 24hrs in the Sanctuary\n- Tap water is clean to drink'
)
ON CONFLICT (key) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();
